### PR TITLE
Add documentation, fix npm module name

### PR DESCRIPTION
**Pull request by mallendeo**
Tested in a Ubuntu VM, works great!

One thing that I noticed is that player keeps playing when navigating.

### CODE REVIEW

**Comment by RSATom** [comment]
Thank you! Will merge it at evening.

**Comment by RSATom** [comment]
> One thing that I noticed is that player keeps playing when navigating.

Could you please explain in little bit more details?

**Comment by mallendeo** [comment]
I mean, the stream plays the first page load, then if I go to another url like google, it keeps playing in the background (noticed because some cameras have sound enabled). If I go back to app://host/index.html, it'll play again and produce echo since it's playing twice.

**Comment by RSATom** [comment]
Thanks, it's definitely a bug.

**Comment by Ivshti** [comment]
I'm guessing just close libvlc on some destructor. Unfortunately I don't know any more than this. 

I stumbled on to another, more serious issue. The behaviour is as follows
1. open a video in webcihmera.js
2. 5-6 seconds, close it
3. another few seconds after that open another
(do that once or a few times)
4. the whole app crashes.

Could be a bug in Electron / Chromium or it could be a bug in webchimera.js. Or a bug in libvlc induced by not doing close properly. I'll investigate :) Happens with vlc 2.1.x and electron 0.26, my own builds

**Comment by RSATom** [comment]
It could be related to garbage collector logic. I didn't got deeply to this question yet.

**Comment by Ivshti** [comment]
I cannot reproduce it on my other installation, which is running slightly older webchimera.js, the same VLC version.
Weird.

**Comment by RSATom** [comment]
Can you get backtrace? It could be tricky since at least `nw.js` runs multiple processes and it's hard predict in which our module runs.

**Comment by Ivshti** [comment]
I honestly don't know how to do that. What I'll do is enable all debugging logs, both for Electron and VLC.

Electron also runs multiple processes.

If I use something primitive like strace, I wouldn't be able to run the app at all - that's how much the logging of everything slows down stuff.

**Comment by RSATom** [comment]
Not a big problem, I think I will find it, just didn't try play media sequences yet.

**Comment by Ivshti** [comment]
Just managed to reproduce it. Will revert back to the old commit and make sure it's not present there.

**Comment by Ivshti** [comment]
This just happened on one single video, and I noticed spikes in RAM usage, so I am thinking that it can be some kind of auto-kill behavior on heavy memory allocation.

**Comment by RSATom** [comment]
hmm... intresting

**Comment by RSATom** [comment]
How big spikes did you see? Is it something about 1.5-2G for single process?

**Comment by Ivshti** [comment]
Nothing of the sort. 300-400MB. When the torrent streaming stops (whole thing is buffered) it's 100-200MB. So this theory is absurd now. It could still be related to memory (de)allocation.

**Comment by RSATom** [comment]
Applied, Thanks!

**Pull request merged**
